/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tepach.vistas;

import Atxy2k.CustomTextField.RestrictedTextField;
import com.tepach.modelo.GetSet;

import com.tepach.modelo.M_cliente;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author inspector
 */
public class jp_cliente extends javax.swing.JPanel {

    /**
     * Creates new form jp_cliente
     */
    public jp_cliente() {
        initComponents();

    }
    private String id, user, tipo;
    DefaultTableModel model;

    public jp_cliente(GetSet gs) {
        initComponents();
        id = gs.getId();
        user = gs.getUser();
        tipo = gs.getTipo();
        new RestrictedTextField(jtf_nucliente).setLimit(30);
        model = (DefaultTableModel) jtbl_Consulta.getModel();
        llenaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtf_nucliente = new javax.swing.JTextField();
        jrb_nuevo = new javax.swing.JRadioButton();
        jrb_consultar = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_Consulta = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(24, 143, 231));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/imagen/LINEAGRANDE.png"))); // NOI18N

        jtf_nucliente.setBackground(new java.awt.Color(24, 143, 231));
        jtf_nucliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtf_nucliente.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nucliente.setText("jTextField1");
        jtf_nucliente.setBorder(null);
        jtf_nucliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nuclienteActionPerformed(evt);
            }
        });

        jrb_nuevo.setBackground(new java.awt.Color(24, 143, 231));
        buttonGroup1.add(jrb_nuevo);
        jrb_nuevo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jrb_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jrb_nuevo.setSelected(true);
        jrb_nuevo.setText("Nuevo Cliente");
        jrb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_nuevoActionPerformed(evt);
            }
        });

        jrb_consultar.setBackground(new java.awt.Color(24, 143, 231));
        buttonGroup1.add(jrb_consultar);
        jrb_consultar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jrb_consultar.setForeground(new java.awt.Color(255, 255, 255));
        jrb_consultar.setText("Consultar Cliente");
        jrb_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_consultarActionPerformed(evt);
            }
        });

        jtbl_Consulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtbl_Consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre del cliente", "Fecha de reistro", "Hora de registro", "Registrado por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbl_Consulta.setEnabled(false);
        jtbl_Consulta.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jtbl_Consulta);
        if (jtbl_Consulta.getColumnModel().getColumnCount() > 0) {
            jtbl_Consulta.getColumnModel().getColumn(0).setResizable(false);
            jtbl_Consulta.getColumnModel().getColumn(1).setResizable(false);
            jtbl_Consulta.getColumnModel().getColumn(2).setResizable(false);
            jtbl_Consulta.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_nuevo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_nucliente, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jrb_consultar))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jrb_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_nucliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_consultar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_consultarActionPerformed
        if (jrb_consultar.isSelected()) {
            jtf_nucliente.disable();
            jtbl_Consulta.enable();
        }
    }//GEN-LAST:event_jrb_consultarActionPerformed

    private void jrb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_nuevoActionPerformed
        // TODO add your handling code here:
        if (jrb_nuevo.isSelected()) {
            jtf_nucliente.enable();
            jtbl_Consulta.disable();
        }
    }//GEN-LAST:event_jrb_nuevoActionPerformed

    private void jtf_nuclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nuclienteActionPerformed
        // TODO add your handling code here:
        GetSet gs = new GetSet();
        M_cliente mc = new M_cliente();
        gs.setC_nombre(jtf_nucliente.getText());
        gs.setId(id);
        mc.setCliente(gs);
        llenaTabla();

    }//GEN-LAST:event_jtf_nuclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrb_consultar;
    private javax.swing.JRadioButton jrb_nuevo;
    private javax.swing.JTable jtbl_Consulta;
    private javax.swing.JTextField jtf_nucliente;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla() {
        model.setNumRows(0);
    }

    private void agregarfila(Object[] datos) {
        //new Object[]{nombre.getText(),apellido.getText(),edd, profesion.getText(),rp}
        model.addRow(datos);
    }

    private void llenaTabla() {
        limpiarTabla();
        jtbl_Consulta.getTableHeader().disable();
        M_cliente mu = new M_cliente();
        try {

            
            ResultSet a = mu.getClientes();
            while (a.next()) {
                agregarfila(new Object[]{a.getString(1), a.getString(2), a.getString(3), a.getString(4)});
            }
            mu.CloseDB();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
        mu.CloseDB();
    }
}
