/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tepach.vistas;

import com.tepach.modelo.GetSet;
import com.tepach.modelo.M_Usuario;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author inspector
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        super("CF Escaner - Iniciar Sesión");
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp_inicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_user = new javax.swing.JTextField();
        jpf_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_logo.setBackground(new java.awt.Color(24, 143, 231));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/imagen/CF lineas bco.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dubai Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout jp_logoLayout = new javax.swing.GroupLayout(jp_logo);
        jp_logo.setLayout(jp_logoLayout);
        jp_logoLayout.setHorizontalGroup(
            jp_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_logoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_logoLayout.setVerticalGroup(
            jp_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_logoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jp_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 420));

        jp_inicio.setBackground(new java.awt.Color(12, 79, 135));
        jp_inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTRASEÑA");
        jp_inicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Iniciar Sesión");
        jp_inicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, -1));

        jLabel6.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/imagen/linea.png"))); // NOI18N
        jp_inicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 200, -1));

        jLabel7.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USUARIO");
        jp_inicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, -1));

        jLabel8.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/imagen/linea.png"))); // NOI18N
        jp_inicio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, -1));

        jtf_user.setBackground(new java.awt.Color(12, 79, 135));
        jtf_user.setFont(new java.awt.Font("Dubai Light", 0, 13)); // NOI18N
        jtf_user.setForeground(new java.awt.Color(255, 255, 255));
        jtf_user.setBorder(null);
        jtf_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_userMouseClicked(evt);
            }
        });
        jtf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_userActionPerformed(evt);
            }
        });
        jp_inicio.add(jtf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 170, 195, 20));

        jpf_pass.setBackground(new java.awt.Color(12, 79, 135));
        jpf_pass.setFont(new java.awt.Font("Dubai Light", 0, 13)); // NOI18N
        jpf_pass.setForeground(new java.awt.Color(255, 255, 255));
        jpf_pass.setBorder(null);
        jpf_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpf_passMouseClicked(evt);
            }
        });
        jp_inicio.add(jpf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 240, 195, 20));

        jPanel3.setBackground(new java.awt.Color(24, 143, 231));

        jLabel9.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Loguear");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jp_inicio.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 80, 40));

        jPanel1.setBackground(new java.awt.Color(224, 55, 55));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_inicio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 30, 20));

        jPanel2.setBackground(new java.awt.Color(141, 197, 239));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_inicio.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 20));

        getContentPane().add(jp_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 340, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_userMouseClicked
        // TODO add your handling code here:
        jtf_user.setText("");
    }//GEN-LAST:event_jtf_userMouseClicked

    private void jtf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_userActionPerformed

    private void jpf_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_passMouseClicked
        // TODO add your handling code here:
        jpf_pass.setText("");
    }//GEN-LAST:event_jpf_passMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        GetSet gs = new GetSet();
        jLabel7.setFocusable(true);
        M_Usuario mu = new M_Usuario();
        String tipo = null, user, id = null, u = null, p = null;
        if (validaCampos()) {
            gs.setPass(jpf_pass.getText());
            gs.setUser(jtf_user.getText());

            try {

                ResultSet a = mu.GetU(gs);
                if (!a.isBeforeFirst()) {
                    JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta", "Verifique sus datos", JOptionPane.INFORMATION_MESSAGE);
                    mu.CloseDB();
                } else {
                    while (a.next()) {
                        gs.setUser(a.getString(2));
                        gs.setPass(a.getString(3));
                        gs.setTipo(a.getString(4));
                        gs.setId(a.getString(1));
                    }
                    if (gs.getTipo().equals("admin")|| gs.getTipo().equals("super")||gs.getTipo().equals("opera")) {
                        V_Admin Vadmin=new V_Admin(gs);
                        Vadmin.setVisible(true);
                        this.setVisible(false);
                        mu.CloseDB();
                    } else {
                        mu.CloseDB();
                    }
                    mu.CloseDB();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getSQLState(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (jtf_user.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa tú usuario", "Error - Validacion de Datos", JOptionPane.ERROR_MESSAGE);
            } else if (jpf_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa la contraseña", "Error - Validacion de Datos", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Ingresa usuario y/o contraseña", "Error - Validacion de Datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jLabel9.setCursor(Cursor.getPredefinedCursor(HAND_CURSOR));
    }//GEN-LAST:event_jLabel9MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jp_inicio;
    private javax.swing.JPanel jp_logo;
    private javax.swing.JPasswordField jpf_pass;
    private javax.swing.JTextField jtf_user;
    // End of variables declaration//GEN-END:variables
  private boolean validaCampos() {
        boolean validar = false;
        if (jtf_user.getText().isEmpty() || jpf_pass.getText().isEmpty()) {
            validar = false;
        } else {
            validar = true;
        }
        return validar;
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/tepach/imagen/bar-code-scanner.png"));
        return retValue;
    }
}
